#!/bin/bash
source /usr/local/bin/delFiliter
deleteOption(){
	clear
    while true; do
        read -p "Enter table name or (write exit): " name
        if [[ "$name" == "exit" ]]; then
            echo "Exiting..."
            exit 0
        fi
        if [[ "$name" =~ ^[a-z][a-zA-Z0-9_]*$ ]]; then
            if [[ -f "$1/$name" ]]; then
		  clear 
		 echo
        	echo "===================================="
       		 echo "Delete from table"
       		 echo "===================================="
       		 echo "1. Delete all records : "
        	echo "2. Delete based Attribute value : "
       		 echo "3. Exit"
       		 echo "===================================="
	     

		  read -p "Enter value (1-3): " choice
		  echo "$1/$name"
        	 case $choice in
                1)
                        sed -i 'd' $1/$name
                        ;;
                2)
			read -p "write as this pattern \"attribute\" \"operator\" \"value\" : " attribute operator value
			del_filiter "$1/$name" "$attribute" "$operator" "$value"
                        ;;
                3)
			exit 1
                        ;;

                *)	
			echo "invalied Value"
                        ;;
                esac
     
           else
                break
            fi
        else
            echo "Invalid table name!"
            echo "The name must:"
            echo "   - Start with a lowercase letter."
            echo "   - Contain only letters, numbers, and underscores (_)."
        fi
	done

}
